- docs/admin/quickstart.md
I tried to go through these steps and found a couple of missing nuances
> Enhance quickstart guide

- CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `0.1.1` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- Adjust social card description [[#119](https://github.com/opencloud-eu/docs/pull/119)]
- Fix docker images names [[#115](https://github.com/opencloud-eu/docs/pull/115)]
> 🎉 Release 0.1.1

- docusaurus.config.ts
fixes: https://github.com/opencloud-eu/docs/issues/137
> Add syntax hilighting for bash

- docs/admin/20-getting-started/30-docker.md
The code block in section [4. Start OpenCloud](https://docs.opencloud.eu/docs/admin/getting-started/docker#4-start-opencloud) starts the container in interactive mode with an allocated pseudo-tty (`-it`).
I changed it to start the container in detached (`-d`) mode, which should be the more common mode when running services, IMHO.
I appreciate it, if you accept this small contribution.
> Start OpenCloud in detached instead of interactive mode

- CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.4.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- Add note that bare metal is exclusively community supported [[#156](https://github.com/opencloud-eu/docs/pull/156)]
- Start OpenCloud in detached instead of interactive mode [[#162](https://github.com/opencloud-eu/docs/pull/162)]
> 🎉 Release 1.4.0

- docs/admin/40-maintenance/20-backup.md
Refined text and text format in the backup tutorial
> Refining the text in backup tutorial

- CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.6.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- Refining the text in backup tutorial [[#170](https://github.com/opencloud-eu/docs/pull/170)]
- Insert a disclaimer in Bare-Metal Tutorial [[#167](https://github.com/opencloud-eu/docs/pull/167)]
> 🎉 Release 1.6.0

- docs/admin/10-welcome/20-features.md
- docs/admin/10-welcome/index.md
- docs/admin/20-getting-started/10-requirements.md
- docs/admin/30-configuration/100-storage-decomposeds3.md
- docs/admin/30-configuration/80-storage-posix.md
New cleaned PR with PosixFS docs.
> Add Posixfs admin documentation 

- docs/admin/20-getting-started/30-other/40-bare-metal.md
fixed url in the https://docs.opencloud.eu/docs/admin/getting-started/other/bare-metal
> fix url in the bare-metal

- CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.11.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- Add TUS [[#208](https://github.com/opencloud-eu/docs/pull/208)]
- fix url in the bare-metal [[#211](https://github.com/opencloud-eu/docs/pull/211)]
- Fix broken favicon on firefox [[#205](https://github.com/opencloud-eu/docs/pull/205)]
> 🎉 Release 1.11.0

- docs/admin/30-configuration/30-keycloak.md
This PR adds detailed documentation for the Keycloak integration with OpenCloud, replacing the empty draft page with comprehensive content.
- Overview of OpenCloud's authentication strategy
- Step-by-step setup instructions with Docker Compose
- OpenCloud configuration guide
- Detailed client configuration for all client types:
- Web client
- Desktop client
- Mobile apps (Android/iOS)
- Additional clients (Cyberduck)
- Advanced configuration (Backchannel Logout)
- Troubleshooting advice
- User and group management overview
- Addresses #97 - "Document how to Integrate Keycloak / external Idp"
- Complements opencloud-eu/opencloud#589 - "Harmonize Keycloak Client Configurations with Built-in IdP"
> Add comprehensive Keycloak integration documentation

- .batchfile
- .gitignore
- .woodpecker/build.yaml
- package.json
Adds a ci step to fetch the design-system docs from the web repository so they get included in the final build of the docs.
Also adds the command `pnpm fetch-design-system-docs` to fetch them locally. Run this before running `pnpm start` to include the design-systems docs in your local build.
refs https://github.com/opencloud-eu/web/issues/217
> Add design-system docs to build

- assets/likec4/README.md
Enhances the LikeC4 README with:
- Better overview of C4 model concepts
- Information about deployed diagrams at docs.opencloud.eu/likec4/
- Improved rendering instructions and workflow
- More structured documentation
@micbar @AlexAndBear please review these documentation improvements.
> Improve LikeC4 README documentation

- docs/admin/getting-started/other/bare-metal.md
At least with GNU make the `-C` option is not target specific. So for now we need two make calls.
Fixes #216
> Fix build instruction

- CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.20.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- Rename docker to container in admin -> getting started [[#259](https://github.com/opencloud-eu/docs/pull/259)]
- add note, that the raspberry pi installation is for private use [[#260](https://github.com/opencloud-eu/docs/pull/260)]
- Add more doc about the collaborative mode [[#254](https://github.com/opencloud-eu/docs/pull/254)]
- Rewrite desktop installation [[#255](https://github.com/opencloud-eu/docs/pull/255)]
> 🎉 Release 1.20.0

- docs/admin/configuration/radicale-integration.md
Related Issue: https://github.com/opencloud-eu/opencloud/issues/206
> Add some words about the Radicale integration

- docs/admin/resources/common-issues.md
> fix admin password issue

- CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.28.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- translation tutorial sidebar iOS app [[#314](https://github.com/opencloud-eu/docs/pull/314)]
- undraft the iOS articles [[#312](https://github.com/opencloud-eu/docs/pull/312)]
> 🎉 Release 1.28.0

- CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.33.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- added that webdav info need to be enabled in the preferences [[#335](https://github.com/opencloud-eu/docs/pull/335)]
- Android app tutorials english [[#323](https://github.com/opencloud-eu/docs/pull/323)]
> 🎉 Release 1.33.0

- docs/admin/resources/common-issues.md
- docs/admin/resources/demo-user.md
- docs/admin/resources/lifecycle.md
- docs/admin/resources/release-notes.md
part of https://github.com/opencloud-eu/opencloud/issues/1029
We need explain users a reason major release so I created `release notes` page and placed it close to `release lifecycle`
There was suggestion to put it close to upgrade section (https://docs.opencloud.eu/docs/admin/maintenance/update) but in my opinion, I placed it in the right place.
I have tried to briefly explain the reason of major release. If you have any suggestions or recommendations, please let me know.
> release notes for 3.0.0 rolling release

- CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.34.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- Mail Notifications [[#343](https://github.com/opencloud-eu/docs/pull/343)]
- move release notes to the upgrade part and put it together under one … [[#342](https://github.com/opencloud-eu/docs/pull/342)]
- improve release notes [[#340](https://github.com/opencloud-eu/docs/pull/340)]
- release notes for 3.0.0 rolling release [[#338](https://github.com/opencloud-eu/docs/pull/338)]
- Updated Link in Web Applications …
> 🎉 Release 1.34.0

- CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.36.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- publish 3.1.0 release in the docs [[#352](https://github.com/opencloud-eu/docs/pull/352)]
- change /home/chaser to /home/user [[#348](https://github.com/opencloud-eu/docs/pull/348)]
> 🎉 Release 1.36.0

- CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.37.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- add libre graph api url to server documentation [[#357](https://github.com/opencloud-eu/docs/pull/357)]
- rewrite the raspberry pi tutorial to match to the new compose repo [[#355](https://github.com/opencloud-eu/docs/pull/355)]
- change structure for deployment with docker compose [[#353](https://github.com/opencloud-eu/docs/pull/353)]
- enhancement(docs): add cdperf documentation …
> 🎉 Release 1.37.0

- docs/user/admin/settings.md
- docs/user/admin/web-dav.md
> Rework User Admin Dokus

- docs/user/spaces/add-user.md
- docs/user/spaces/create.md
- docs/user/spaces/customize.md
- docs/user/spaces/delete.md
- docs/user/spaces/enable-disable.md
- docs/user/spaces/quota.md
- docs/user/spaces/rename.md
- docs/user/spaces/why-spaces.md
> Rework user spaces dokus

- docs/admin/welcome/datasheet.md
- docs/admin/welcome/features.md
- docs/admin/welcome/index.md
> rework admin welcome docs

- CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.41.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- rework user admin de and set kubernetes to draft:false [[#409](https://github.com/opencloud-eu/docs/pull/409)]
> 🎉 Release 1.41.0

- docs/admin/getting-started/container/docker-compose/docker-external-proxy.md
[Clone the OpenCloud Repository](https://github.com/opencloud-eu/docs/blob/main/docs/admin/getting-started/container/docker-compose/docker-external-proxy.md#clone-the-opencloud-repository) is unneeded as readers are instructed to do this into [Configure and start OpenCloud](https://github.com/opencloud-eu/docs/blob/main/docs/admin/getting-started/container/docker-compose/docker-external-proxy.md#configure-and-start-opencloud) section.
> unneeded "Clone the OpenCloud Repository" section

- docs/user/desktop-client/file-names.md
@TheOneRing could you please check if all is correct what I wrote?
> add file name rules for desktop

- docs/admin/configuration/authentication-and-user-management/keycloak.md
- docs/admin/configuration/radicale-integration.md
- docs/admin/configuration/storage/decomposeds3.md
- docs/admin/getting-started/container/docker-compose/keycloak.md
- docs/admin/maintenance/migrate.md
- docs/admin/resources/common-issues.md
- static/env-vars/app-registry_readme.md
- static/env-vars/proxy_readme.md
- static/env-vars/search_readme.md
> change: remove all opencloud_full references

- CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.52.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- removed soon from ios android [[#465](https://github.com/opencloud-eu/docs/pull/465)]
- publish release note 3.5.0 [[#466](https://github.com/opencloud-eu/docs/pull/466)]
> 🎉 Release 1.52.0
