opencloud-eu/docs

docs/user/desktop-client/installation.md, docs/user/desktop-client/set-up.md, docs/user/desktop-client/settings.md, docs/user/desktop-client/sync-settings.md, docs/user/desktop-client/uninstall.md, docs/user/files-and-folders/activity.md, docs/user/files-and-folders/create-rename-move.md, docs/user/files-and-folders/delete-restore.md, docs/user/files-and-folders/link.md, docs/user/files-and-folders/search.md, docs/user/files-and-folders/tags.md, docs/user/files-and-folders/versions.md, docs/user/general/account-settings.md, docs/user/general/file-list-adjustments.md, docs/user/general/overview.md, docs/user/general/view-modes.md, docs/user/roles/share-roles.md, docs/user/roles/space-roles.md, docs/user/sharing/external.md, docs/user/sharing/file-drop.md, docs/user/sharing/internal.md, docs/user/spaces/add-user.md, docs/user/spaces/create.md, docs/user/spaces/customize.md, docs/user/spaces/delete.md, docs/user/spaces/quota.md
=> Improve styling for english documentation

docs/user/intro.md
With adding a title and an id the Welcome Page was not correct.
=> Fix intro page

docusaurus.config.ts, src/css/custom.css
accessible link color with enough contrast according to AA contrast requirement. enables light mode again.
note: do not merge until we got feedback from Ivonne. This is just a proposal, we might still need support from a color professional 🧑‍🎨
fixes https://github.com/opencloud-eu/docs/issues/49
=> Enable light mode with accessible link color

docs/admin/installation/bare-metal.md, docs/admin/installation/common-issues.md, docs/admin/installation/docker-compose.md, docs/admin/installation/docker.md
refine wording and design in installation guides
=> Enhance installation guides

.woodpecker/build.yaml
Adds production deployment when event == tag.
=> feat: add production server

CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.0.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- Preset for Navigation Structure [[#117](https://github.com/opencloud-eu/docs/pull/117)]
=> 🎉 Release 1.0.0

CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.0.2` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- Fix bare metal link [[#127](https://github.com/opencloud-eu/docs/pull/127)]
=> 🎉 Release 1.0.2

docs/admin/20-getting-started/40-bare-metal.md
=> correct build command

CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.2.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- Enhance space roles [[#144](https://github.com/opencloud-eu/docs/pull/144)]
- Adjust the english for Desktop Client & Admin [[#142](https://github.com/opencloud-eu/docs/pull/142)]
- correct build command [[#143](https://github.com/opencloud-eu/docs/pull/143)]
- Make generate  build as a single command [[#139](https://github.com/opencloud-eu/docs/pull/139)]
=> 🎉 Release 1.2.0

docs/admin/20-getting-started/40-bare-metal.md
- Add note that bare metal is exclusively community supported
- This note was already included in the Technical Datasheet, but seems to be overlooked
=> Add note that bare metal is exclusively community supported

CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.4.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- Add note that bare metal is exclusively community supported [[#156](https://github.com/opencloud-eu/docs/pull/156)]
- Start OpenCloud in detached instead of interactive mode [[#162](https://github.com/opencloud-eu/docs/pull/162)]
=> 🎉 Release 1.4.0

docs/admin/10-welcome/30-datasheet.md
Add KQL to APIs, we missed to list that one so far.
=> Add KQL to APIs

docs/admin/20-getting-started/40-bare-metal.md
Insert a disclaimer and required a go version
=> Insert a disclaimer in Bare-Metal Tutorial

docs/admin/20-getting-started/40-bare-metal.md
changed the disclaimer text and removed the node block
=> Changing disclaimer text

CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.7.1` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- Recover release notes [[#175](https://github.com/opencloud-eu/docs/pull/175)]
=> 🎉 Release 1.7.1

docs/admin/50-resources/10-whats-new.md
- 2.0.0: File Native Backups with PosixFS
- 1.1.0: Material Design Color Roles
=> Add release notes for version 1.1.0 and 2.0.0

CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.10.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- fix typos in backup [[#202](https://github.com/opencloud-eu/docs/pull/202)]
- change structure of folder getting started [[#200](https://github.com/opencloud-eu/docs/pull/200)]
=> 🎉 Release 1.10.0

CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.12.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- Add dev docs [[#217](https://github.com/opencloud-eu/docs/pull/217)]
=> 🎉 Release 1.12.0

CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.15.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- Add some generic bits about integrating with external IDP [[#227](https://github.com/opencloud-eu/docs/pull/227)]
=> 🎉 Release 1.15.0

docusaurus.config.ts, package.json, pnpm-lock.yaml
Needed to port https://github.com/opencloud-eu/opencloud/pull/568
=> Add mermaid support 

docs/dev/20-web/60-design-system/index.md
=> Add design system reference to web dev docs

docs/admin/welcome/index.md
=> removed "coming soon"

CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.19.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- Improve LikeC4 README documentation [[#250](https://github.com/opencloud-eu/docs/pull/250)]
- removed "coming soon" [[#253](https://github.com/opencloud-eu/docs/pull/253)]
- Fix build instruction [[#224](https://github.com/opencloud-eu/docs/pull/224)]
=> 🎉 Release 1.19.0

docs/admin/configuration/storage/posixfs.md
Story https://github.com/opencloud-eu/opencloud/issues/629
=> Add more doc about the collaborative mode

CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.21.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- Add own category for docker installation in admin getting started guide [[#261](https://github.com/opencloud-eu/docs/pull/261)]
=> 🎉 Release 1.21.0

docs/admin/resources/faq.md, docs/admin/welcome/datasheet.md, docs/admin/welcome/faq.md, docs/admin/welcome/features.md
First FAQ draft from issue Docu FAQ https://github.com/opencloud-eu/docs/issues/204
=> Create FAQ site

i18n/de/docusaurus-plugin-content-docs/current/user/ios-app/installation.md, i18n/de/docusaurus-plugin-content-docs/current/user/ios-app/overview.md, i18n/de/docusaurus-plugin-content-docs/current/user/ios-app/set-up.md, i18n/de/docusaurus-plugin-content-docs/current/user/ios-app/settings.md
refined text in iOS app German translation settings
=> Ios app german translation settings

docs/admin/resources/lifecycle.md
page was erroneously still in draft mode, removed draft status.
=> set lifecycle page live

docs/admin/configuration/activitylog.mdx, docs/admin/configuration/app-provider.mdx, docs/admin/configuration/app-registry.mdx, docs/admin/configuration/audit.mdx, docs/admin/configuration/auth-app.mdx, docs/admin/configuration/auth-basic.mdx, docs/admin/configuration/auth-bearer.mdx, docs/admin/configuration/auth-machine.mdx, docs/admin/configuration/auth-service.mdx, docs/admin/configuration/clientlog.mdx, docs/admin/configuration/collaboration.mdx
=> added configvars in admin a-c

CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.25.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- add future releasedates and semver [[#284](https://github.com/opencloud-eu/docs/pull/284)]
=> 🎉 Release 1.25.0

docs/admin/configuration/eventhistory.mdx, docs/admin/configuration/frontend.mdx, docs/admin/configuration/gateway.mdx, docs/admin/configuration/global.mdx, docs/admin/configuration/graph.mdx, docs/admin/configuration/groups.mdx, docs/admin/configuration/idm.mdx, docs/admin/configuration/idp.mdx, docs/admin/configuration/invitations.mdx, docs/admin/configuration/nats.mdx, docs/admin/configuration/notifications.mdx, docs/admin/configuration/ocdav.mdx, docs/admin/configuration/ocm.mdx, docs/admin/configuration/ocs.mdx
=> added configvars in admin d-o

i18n/de/docusaurus-plugin-content-docs/current/user/desktop-client/installation.md
German translation of installation tutorial
=> german translation installation

docs/admin/resources/lifecycle.md
part of https://github.com/opencloud-eu/opencloud/issues/883
=> publish 2.3.0 release in the docs

docs/user/ios-app/search.md, docs/user/ios-app/shares/invite.md, docs/user/ios-app/shares/links.md, docs/user/ios-app/shortcuts.md, i18n/de/docusaurus-plugin-content-docs/current/user/ios-app/search.md, i18n/de/docusaurus-plugin-content-docs/current/user/ios-app/shares/invite.md, i18n/de/docusaurus-plugin-content-docs/current/user/ios-app/shares/links.md, i18n/de/docusaurus-plugin-content-docs/current/user/ios-app/shortcuts.md
=> undraft the iOS articles

CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.32.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- removed unnecessary links [[#329](https://github.com/opencloud-eu/docs/pull/329)]
=> 🎉 Release 1.32.0

docs/dev/server/index.md
=> add libre graph api url to server documentation

docs/admin/resources/lifecycle.md
=> update release list

docs/admin/resources/lifecycle.md
part of https://github.com/opencloud-eu/opencloud/issues/1254
=> publish release notes 3.2.0

CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.43.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- adjust link in the external proxy docs [[#416](https://github.com/opencloud-eu/docs/pull/416)]
=> 🎉 Release 1.43.0

docs/admin/configuration/authentication-and-user-management/keycloak-user.md, docs/user/common-issues.md
@TheOneRing could you please have a look if it makes sense what I wrote?
=> add common issues to users, desktop client

docs/admin/welcome/index.md, docs/user/intro.md, package-lock.json
introducing links to the user intro & fixing 2 icons
=> introducing links to the user intro & fixing 2 icons

docs/admin/resources/lifecycle.md
part of https://github.com/opencloud-eu/opencloud/issues/1327
=> publish release note 3.3.0

CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.47.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- remove draft: true and add missing pics in german part for Android [[#438](https://github.com/opencloud-eu/docs/pull/438)]
=> 🎉 Release 1.47.0

CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `1.50.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- change: remove all opencloud_full references [[#454](https://github.com/opencloud-eu/docs/pull/454)]
=> 🎉 Release 1.50.0

docs/admin/welcome/features.md
removed "soon" from ios and android as the apps are available
=> removed soon from ios android
